export const BOOKS = [
  { slug: "gen", name: "Genesis", aliases: [], abbrevs: ["Gen", "Ge"] },
  { slug: "exod", name: "Exodus", aliases: [], abbrevs: ["Exod", "Ex"] },
  { slug: "lev", name: "Leviticus", aliases: [], abbrevs: ["Lev", "Le"] },
  { slug: "num", name: "Numbers", aliases: [], abbrevs: ["Num", "Nu"] },
  { slug: "deut", name: "Deuteronomy", aliases: [], abbrevs: ["Deut", "Dt"] },
  { slug: "josh", name: "Joshua", aliases: [], abbrevs: ["Josh", "Jos"] },
  { slug: "judg", name: "Judges", aliases: [], abbrevs: ["Judg", "Jdg"] },
  { slug: "ruth", name: "Ruth", aliases: [], abbrevs: ["Ru"] },
  {
    slug: "1sam",
    name: "1 Samuel",
    aliases: ["I Samuel"],
    abbrevs: ["1Sam", "1 Sa", "ISam"],
  },
  {
    slug: "2sam",
    name: "2 Samuel",
    aliases: ["II Samuel"],
    abbrevs: ["2Sam", "2 Sa", "IISam"],
  },
  {
    slug: "1kgs",
    name: "1 Kings",
    aliases: ["I Kings"],
    abbrevs: ["1Kgs", "1 Ki", "IKgs"],
  },
  {
    slug: "2kgs",
    name: "2 Kings",
    aliases: ["II Kings"],
    abbrevs: ["2Kgs", "2 Ki", "IIKgs"],
  },
  {
    slug: "1chr",
    name: "1 Chronicles",
    aliases: ["I Chronicles"],
    abbrevs: ["1Chr", "1 Ch", "IChr"],
  },
  {
    slug: "2chr",
    name: "2 Chronicles",
    aliases: ["II Chronicles"],
    abbrevs: ["2Chr", "2 Ch", "IIChr"],
  },
  { slug: "ezra", name: "Ezra", aliases: [], abbrevs: [] },
  { slug: "neh", name: "Nehemiah", aliases: [], abbrevs: ["Neh"] },
  { slug: "esth", name: "Esther", aliases: [], abbrevs: ["Esth", "Es"] },
  { slug: "job", name: "Job", aliases: [], abbrevs: ["Jb"] },
  { slug: "ps", name: "Psalms", aliases: [], abbrevs: ["Ps", "Psa", "Psalm"] },
  { slug: "prov", name: "Proverbs", aliases: [], abbrevs: ["Prov", "Pr"] },
  { slug: "eccl", name: "Ecclesiastes", aliases: [], abbrevs: ["Eccl", "Ec"] },
  {
    slug: "song",
    name: "Song of Solomon",
    aliases: [],
    abbrevs: ["Song", "So", "SOS"],
  },
  { slug: "isa", name: "Isaiah", aliases: [], abbrevs: ["Isa"] },
  { slug: "jer", name: "Jeremiah", aliases: [], abbrevs: ["Jer"] },
  { slug: "lam", name: "Lamentations", aliases: [], abbrevs: ["Lam"] },
  { slug: "ezek", name: "Ezekiel", aliases: [], abbrevs: ["Ezek", "Eze"] },
  { slug: "dan", name: "Daniel", aliases: [], abbrevs: ["Da"] },
  { slug: "hos", name: "Hosea", aliases: [], abbrevs: ["Ho"] },
  { slug: "joel", name: "Joel", aliases: [], abbrevs: ["Joe"] },
  { slug: "amos", name: "Amos", aliases: [], abbrevs: [] },
  { slug: "obad", name: "Obadiah", aliases: [], abbrevs: ["Obad"] },
  { slug: "jonah", name: "Jonah", aliases: [], abbrevs: ["Jon"] },
  { slug: "mic", name: "Micah", aliases: [], abbrevs: [] },
  { slug: "nah", name: "Nahum", aliases: [], abbrevs: ["Na"] },
  { slug: "hab", name: "Habakkuk", aliases: [], abbrevs: [] },
  { slug: "zeph", name: "Zephaniah", aliases: [], abbrevs: ["Zeph"] },
  { slug: "hag", name: "Haggai", aliases: [], abbrevs: ["Hag"] },
  { slug: "zech", name: "Zechariah", aliases: [], abbrevs: ["Zech", "Zec"] },
  { slug: "mal", name: "Malachi", aliases: [], abbrevs: ["Mal"] },
  { slug: "matt", name: "Matthew", aliases: [], abbrevs: ["Matt", "Mt"] },
  { slug: "mark", name: "Mark", aliases: [], abbrevs: ["Mk", "Mr"] },
  { slug: "luke", name: "Luke", aliases: [], abbrevs: ["Lk", "Lu"] },
  { slug: "john", name: "John", aliases: [], abbrevs: ["Jn", "Joh"] },
  { slug: "acts", name: "Acts", aliases: [], abbrevs: ["Ac"] },
  { slug: "rom", name: "Romans", aliases: [], abbrevs: ["Rom", "Ro"] },
  {
    slug: "1cor",
    name: "1 Corinthians",
    aliases: ["I Corinthians"],
    abbrevs: ["1Cor", "1 Co", "ICor"],
  },
  {
    slug: "2cor",
    name: "2 Corinthians",
    aliases: ["II Corinthians"],
    abbrevs: ["2Cor", "2 Co", "IICor"],
  },
  { slug: "gal", name: "Galatians", aliases: [], abbrevs: ["Gal", "Ga"] },
  { slug: "eph", name: "Ephesians", aliases: [], abbrevs: ["Eph"] },
  { slug: "phil", name: "Philippians", aliases: [], abbrevs: ["Phil", "Php"] },
  { slug: "col", name: "Colossians", aliases: [], abbrevs: ["Col"] },
  {
    slug: "1thess",
    name: "1 Thessalonians",
    aliases: ["I Thessalonians"],
    abbrevs: ["1Thess", "1 Th", "IThess"],
  },
  {
    slug: "2thess",
    name: "2 Thessalonians",
    aliases: ["II Thessalonians"],
    abbrevs: ["2Thess", "2 Th", "IIThess"],
  },
  {
    slug: "1tim",
    name: "1 Timothy",
    aliases: ["I Timothy"],
    abbrevs: ["1Tim", "1 Ti", "ITim"],
  },
  {
    slug: "2tim",
    name: "2 Timothy",
    aliases: ["II Timothy"],
    abbrevs: ["2Tim", "2 Ti", "IITim"],
  },
  { slug: "titus", name: "Titus", aliases: [], abbrevs: ["Tit"] },
  { slug: "phlm", name: "Philemon", aliases: [], abbrevs: ["Phlm", "Phm"] },
  { slug: "heb", name: "Hebrews", aliases: [], abbrevs: ["Heb"] },
  { slug: "jas", name: "James", aliases: [], abbrevs: ["Jas", "Jm"] },
  {
    slug: "1pet",
    name: "1 Peter",
    aliases: ["I Peter"],
    abbrevs: ["1Pet", "1 Pe", "IPet"],
  },
  {
    slug: "2pet",
    name: "2 Peter",
    aliases: ["II Peter"],
    abbrevs: ["2Pet", "2 Pe", "IIPet"],
  },
  {
    slug: "1john",
    name: "1 John",
    aliases: ["I John"],
    abbrevs: ["1John", "1 Jn", "IJohn"],
  },
  {
    slug: "2john",
    name: "2 John",
    aliases: ["II John"],
    abbrevs: ["2John", "2 Jn", "IIJohn"],
  },
  {
    slug: "3john",
    name: "3 John",
    aliases: ["III John"],
    abbrevs: ["3John", "3 Jn", "IIIJohn"],
  },
  { slug: "jude", name: "Jude", aliases: [], abbrevs: ["Jud"] },
  {
    slug: "rev",
    name: "Revelation",
    aliases: ["Revelation of John"],
    abbrevs: ["Rev", "Re"],
  },
] as const;

export type BookSlug = (typeof BOOKS)[number]["slug"];

const nameToSlug = new Map<string, BookSlug>(
  BOOKS.flatMap((book) => [
    [book.name, book.slug],
    ...book.aliases.map((alias) => [alias, book.slug] as const),
    ...book.abbrevs.map((abbrev) => [abbrev, book.slug] as const),
  ]),
);

export function bookNameToSlug(name: string): BookSlug | undefined {
  return nameToSlug.get(name);
}

export function verseKey(
  book: BookSlug,
  chapter: number,
  verse: number,
): string {
  return `${book}.${chapter}.${verse}`;
}
